# Generated by Django 6.0.3 on 2026-03-05 15:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('creator_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('playlist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('occasion', models.CharField(max_length=50)),
                ('generation_status', models.IntegerField(choices=[(1, 'Generating'), (2, 'Generated'), (3, 'Error')], default=1)),
                ('mood_tone', models.IntegerField(choices=[(1, 'Happy'), (2, 'Sad'), (3, 'Upbeat'), (4, 'Romantic'), (5, 'Chill'), (6, 'Epic')])),
                ('voice_type', models.IntegerField(choices=[(1, 'Male Pop'), (2, 'Female Pop'), (3, 'Male Rock'), (4, 'Female Rock'), (5, 'Instrumental Only')])),
                ('lyrics_content', models.CharField(max_length=2000)),
                ('duration', models.IntegerField()),
                ('audio_file_url', models.CharField(max_length=50)),
                ('share_url', models.CharField(max_length=50)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
