# Generated by Django 6.0.3 on 2026-04-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_song_suno_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyrics_content',
        ),
    ]
