# Generated by Django 6.0.3 on 2026-04-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_song_lyrics_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='voice_type',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')]),
        ),
    ]
